trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  displayName: Terraform Installation
  inputs:
    terraformVersion: 'latest'
  
- task: TerraformCLI@0
  displayName: Terraform Init Stage
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/path/path/'
    backendType: 'azurerm'
    environmentServiceName: '[name of the storage principal]'
    providerAzureRmSubscriptionId: '[azure subscription ID]'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: Destroy
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/path/path/'
    environmentServiceName: '[name of the storage principal]'
    providerAzureRmSubscriptionId: '[azure subscription ID]'
    runAzLogin: true
    allowTelemetryCollection: true